CREATE DATABASE ADIVINA_LA_COMUNIDAD;
USE ADIVINA_LA_COMUNIDAD;
CREATE TABLE JUGADOR (
    JUGADOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(50),
    PUNTUACION_MAX INT
);
CREATE TABLE PAIS (
    PAIS_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(250),
    FOTO_BANDERA VARCHAR(250),
    FOTO_COMIDA VARCHAR(250),
    FOTO_LUGAR VARCHAR(250)
);